version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Configuration file for Prometheus
    restart: always

  loki:
    image: grafana/loki:2.8.1
    container_name: loki
    ports:
      - "3100:3100"  # Loki API
    restart: always
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml  # Configuration file for Loki
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:2.8.1
    container_name: promtail
    volumes:
      - /var/log:/var/log  # Mount logs from the host
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml  # Promtail config file
    restart: always
    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default admin password
    ports:
      - "3000:3000"  # Grafana UI
    depends_on:
      - prometheus
      - loki
    restart: always
