version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env.staging
    volumes:
      - .:/app  # mounts full project to /app
    restart: unless-stopped
    environment:
      NODE_ENV: staging
