global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'my_app'
    static_configs:
      - targets: ['localhost:8080']  # Replace with your application's metric endpoint
